name: Deploy GitHub Pages

# 触发条件：在 push 到 hexo 分支后
on:
  push:
    branches:
      - hexo-fs

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo-fs
          persist-credentials: false
          submodules: true
          # fetch-depth: 0

      - name: Prepare Node env
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
          # - name: Set Env
        #     env:
              #       GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
            #     run: |
     #     git config --global user.name 'yszar' # github用户名
     #     git config --global user.email 'yszar@vip.qq.com' # github邮箱
     #       sed -i "s/GITHUB_ACCESS_TOKEN/$GITHUB_ACCESS_TOKEN/g" ./_config.yml

      # build
      - name: Build
        run: |
            npm i --global gulp-cli
            npm i hexo-cli
            npm install
            npx hexo clean
            npx hexo algolia
            npx hexo g
            gulp
       # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CONFIG_NAME: yszar
          GIT_CONFIG_EMAIL: yszar@vip.qq.com
            # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: public

      # Deploy
      - name: Send-HK-BJ
        #uses: appleboy/ssh-action@master
        uses: appleboy/scp-action@master
        with:
          # host: "${{ secrets.ALI_HK_PEM }},${{ secrets.ALI_HK_PEM }}"
          host: "123.57.236.141,47.242.67.157"
          username: root
          key: ${{ secrets.ALI_HK_PEM }}
          port: 22
          source: "public"
          target: "/web/tangjiuyang"
          strip_components: 1
          # sync: true
          #script: |
          #  cd /web/tangjiuyang
          #  git pull origin master
        # uses: easingthemes/ssh-deploy@v2.1.4
        # env:
        #  SSH_PRIVATE_KEY: ${{ secrets.ALI_HK_PEM }}
        #  ARGS: "-avz --delete"
        #  SOURCE: "public"
        #  REMOTE_HOST: ${{ secrets.ALI_HK_IP }}
        #  REMOTE_USER: "root"
        #  TARGET: "/web/tangjiuyang"

          #      - name: Send-BJ
          #        uses: easingthemes/ssh-deploy@v2.1.4
          # env:
          # SSH_PRIVATE_KEY: ${{ secrets.ALI_BJ_PEM }}
          # ARGS: "-avz --delete"
          # SOURCE: "public"
          # REMOTE_HOST: ${{ secrets.ALI_BJ_IP }}
          # REMOTE_USER: "root"
          # TAgit pull
          #"/web/tangjiuyang"
